### ISSUE TITLE
Skipped Logging of Successful Payment

### ISSUE THREAD

**Issue by erinachavez** [naa986/wp-paypal#1]
Hello, 

I'm having an unusual issue with this plugin. We had received a successful payment from one of our wp-paypal buttons, but in the wp PayPal orders menu, it shows up as entirely blank and just titled "order" instead of with an actual order number. Successful payments from before and after are working just fine. What went wrong?

![capture](https://user-images.githubusercontent.com/25967093/37973615-e8a65d36-31a8-11e8-9c53-a89db15d4edb.PNG)
![capture2](https://user-images.githubusercontent.com/25967093/37973616-ea1d1d1c-31a8-11e8-90aa-222ff3697db7.PNG)

**Comment by erinachavez** [comment]
Just to tack on, it seems as if my debugging console has gone completely blank. I opened it up for the first time in a little while, and am puzzled why there is nothing there.
![capture](https://user-images.githubusercontent.com/25967093/37977157-3a80af5a-31b1-11e8-9399-49e9ab3391d2.PNG)

Any advice would be appreciated, thank you!

**Comment by naa986** [comment]
Hi, Do you get any message if you click on the "Reset Log" button?

**Comment by erinachavez** [comment]
![image](https://user-images.githubusercontent.com/25967093/38094031-a6e6e4d6-333a-11e8-8a76-272d4fffdcdb.png)

It has reset and is empty-- I assume this is normal. The one blank order hasn't changed.

**Comment by erinachavez** [comment]
Hello, this issue has repeated itself. I would really appreciate any sort of guidance as to what may be causing this issue. I've looked into PayPal's IPN responses for the two issues, and they seem to have been sent with no problems and with a properly formatted message. I feel something is randomly going wrong when received on the plugin side.

The debugging console has gone blank again as well. I feel that these two issues are related.

**Comment by naa986** [comment]
It looks like the plugin has no issue writing to the log file. Please use the contact form on the site so I can investigate it: https://wphowto.net/contact

**Comment by erinachavez** [comment]
Great thank you! I just messaged you.
